// Generated by Wrangler by running `wrangler types`

interface Env {
	USER_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").UserDurableObject>;
	CHANNEL_DURABLE_OBJECT: DurableObjectNamespace<import("./src/index").ChannelDurableObject>;
}
